spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  application:
    name: reconx-api

  jpa:
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

  sql:
    init:
      mode: never

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

  endpoint:
    health:
      show-details: when-authorized
      probes:
        enabled: true


server:
  port: 8080

  servlet:
    context-path: /api
